stderr="./log/stderr.log"
stdout="./log/stdout.log"

[broker.tcp]
name="tcp"
protocol="tcp"
enable=true
addr="127.0.0.1:1883"
stderr="./log/tcp_stderr.log"
stdout="./log/tcp_stdout.log"

[broker.websocket]
name="websocket"
protocol="websocket"
enable=true
addr="127.0.0.1:1884"
stderr="./log/websocket_stderr.log"
stdout="./log/websocket_stdout.log"
